In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [5]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [6]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [14]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [18]:
print(dataset.target)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [19]:
df['target']=dataset.target

In [20]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [25]:
df['target'].unique()

array([0, 1, 2])

We make only binary type of logistic regression classification so we can remove the target value those they containing value 2

In [23]:
df_copy=df[df['target']!=2]

In [24]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [26]:
df_copy['target'].unique()

array([0, 1])

we have to decide the dependent and independent variable

In [29]:
x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [32]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [33]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int32

In [34]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [39]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((80, 4), (20, 4), (80,), (20,))

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
classification=LogisticRegression(max_iter=200)

In [42]:
classification

LogisticRegression(max_iter=200)

In [43]:
classification.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [45]:
y_pred_log=classification.predict(x_test)

In [46]:
y_pred_log

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

# Calculating the confusion matrix, accuracy, classification report

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [48]:
print(confusion_matrix(y_test,y_pred_log))

[[12  0]
 [ 0  8]]


In [49]:
print(accuracy_score(y_test,y_pred_log))

1.0


In [50]:
print(classification_report(y_test,y_pred_log))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



# Perform Cross Validation

In [51]:
from sklearn.model_selection import KFold

In [52]:
cv=KFold(n_splits=5,shuffle=True)

In [53]:
cv1=KFold(n_splits=5,shuffle=False)

In [55]:
from sklearn.model_selection import cross_val_score

In [58]:
scores=cross_val_score(classification,x_train,y_train,scoring='accuracy',cv=cv)

In [59]:
cross_val_score(classification,x_train,y_train,scoring='accuracy',cv=cv1)

array([1., 1., 1., 1., 1.])

In [61]:
final_score=np.mean(scores)

In [62]:
final_score

1.0